#!/bin/bash

# 🚀 Birthday Party Hall Booking App - Deployment Script
# This script helps you deploy your app to production

echo "🎉 Welcome to the Birthday Party Hall Booking App Deployment!"
echo "=========================================================="

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo "📁 Initializing Git repository..."
    git init
    git add .
    git commit -m "Initial commit - Birthday Party Hall Booking App"
    echo "✅ Git repository initialized"
fi

# Check if remote is set
if ! git remote get-url origin > /dev/null 2>&1; then
    echo "🔗 Please set up your GitHub repository:"
    echo "1. Create a new repository on GitHub"
    echo "2. Run: git remote add origin https://github.com/yourusername/your-repo-name.git"
    echo "3. Run: git push -u origin main"
    echo ""
    read -p "Press Enter when you've set up the GitHub repository..."
fi

echo ""
echo "📋 Deployment Checklist:"
echo "========================"
echo "✅ 1. MongoDB Atlas Setup"
echo "   - Create account at https://www.mongodb.com/atlas"
echo "   - Create free cluster"
echo "   - Get connection string"
echo ""
echo "✅ 2. Stripe Setup"
echo "   - Create account at https://stripe.com"
echo "   - Get API keys from dashboard"
echo ""
echo "✅ 3. Render Setup (Backend)"
echo "   - Create account at https://render.com"
echo "   - Connect GitHub repository"
echo "   - Deploy backend service"
echo ""
echo "✅ 4. Vercel Setup (Frontend)"
echo "   - Create account at https://vercel.com"
echo "   - Connect GitHub repository"
echo "   - Deploy frontend service"
echo ""

echo "🔧 Environment Variables Needed:"
echo "================================"
echo ""
echo "Backend (.env or Render Environment Variables):"
echo "PORT=10000"
echo "MONGO_URI=mongodb+srv://username:password@cluster.mongodb.net/partybooking?retryWrites=true&w=majority"
echo "JWT_SECRET=your-super-secret-jwt-key-change-this-in-production"
echo "STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key_here"
echo "STRIPE_PUBLISHABLE_KEY=pk_test_your_stripe_publishable_key_here"
echo "EMAIL_USER=your-email@gmail.com"
echo "EMAIL_PASS=your-email-app-password"
echo "ADMIN_USERNAME=admin"
echo "ADMIN_PASSWORD=admin123"
echo ""
echo "Frontend (Update in src/App.js):"
echo "REACT_APP_API_URL=https://your-app.onrender.com"
echo "REACT_APP_STRIPE_PUBLISHABLE_KEY=pk_test_your_stripe_publishable_key_here"
echo ""

echo "🧪 Testing Commands:"
echo "===================="
echo ""
echo "Test Backend API:"
echo "curl https://your-app.onrender.com/api/halls"
echo ""
echo "Test Admin Login:"
echo "curl -X POST https://your-app.onrender.com/api/auth/login \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"username\":\"admin\",\"password\":\"admin123\"}'"
echo ""
echo "Create Admin Account:"
echo "curl -X POST https://your-app.onrender.com/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"username\":\"admin\",\"email\":\"admin@example.com\",\"password\":\"admin123\"}'"
echo ""

echo "🎯 Quick Start Commands:"
echo "========================"
echo ""
echo "1. Push to GitHub:"
echo "   git add ."
echo "   git commit -m \"Ready for deployment\""
echo "   git push origin main"
echo ""
echo "2. Deploy Backend (Render):"
echo "   - Go to https://render.com"
echo "   - Create new Web Service"
echo "   - Connect your GitHub repo"
echo "   - Set root directory to 'backend'"
echo "   - Add environment variables"
echo ""
echo "3. Deploy Frontend (Vercel):"
echo "   - Go to https://vercel.com"
echo "   - Create new project"
echo "   - Connect your GitHub repo"
echo "   - Set root directory to 'frontend'"
echo ""

echo "🎉 Your app will be live at:"
echo "Frontend: https://your-app.vercel.app"
echo "Backend: https://your-app.onrender.com"
echo "Admin: https://your-app.vercel.app/admin"
echo ""

echo "📚 For detailed instructions, see DEPLOYMENT.md"
echo "🔧 For Stripe integration help, see stripe-integration.md"
echo "📖 For API testing, use postman_collection.json"
echo ""

echo "Happy Deploying! 🚀" 